### ISSUE TITLE
Deploy as a web app

### ISSUE THREAD

**Issue by TheMousePotato** [Ayushkaushal/Grim_Reaper#11]
It'll be great if you can make this run on a public platform. A guide to deploying a flask app on AWS can be found in https://docker-curriculum.com/. Heroku is also an option.

**Comment by Ayushkaushal** [comment]
I have taken it into consideration @TheMousePotato .

**Comment by Ayushkaushal** [comment]
Deployed here : https://appapp123.herokuapp.com/
